// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: azVx9DM13tZbR2SGxpPJBW
// Component: Ms55rfh3aQ
import * as React from "react"

import { Link, GatsbyLinkProps as LinkProps } from "gatsby"

import * as p from "@plasmicapp/react-web"

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web"

import "@plasmicapp/react-web/lib/plasmic.css"
import * as defaultcss from "../plasmic__default_style.module.css" // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_underhand.module.css" // plasmic-import: azVx9DM13tZbR2SGxpPJBW/projectcss
import * as sty from "./PlasmicNavigationHamburger.module.css" // plasmic-import: Ms55rfh3aQ/css

import HamburgerNavigationIcon from "./icons/PlasmicIcon__HamburgerNavigation" // plasmic-import: cwJrUItrF/icon

export type PlasmicNavigationHamburger__VariantMembers = {}

export type PlasmicNavigationHamburger__VariantsArgs = {}
type VariantPropType = keyof PlasmicNavigationHamburger__VariantsArgs
export const PlasmicNavigationHamburger__VariantProps =
  new Array<VariantPropType>()

export type PlasmicNavigationHamburger__ArgsType = {}
type ArgPropType = keyof PlasmicNavigationHamburger__ArgsType
export const PlasmicNavigationHamburger__ArgProps = new Array<ArgPropType>()

export type PlasmicNavigationHamburger__OverridesType = {
  root?: p.Flex<"div">
  svg?: p.Flex<"svg">
}

export interface DefaultNavigationHamburgerProps {
  className?: string
}

function PlasmicNavigationHamburger__RenderFunc(props: {
  variants: PlasmicNavigationHamburger__VariantsArgs
  args: PlasmicNavigationHamburger__ArgsType
  overrides: PlasmicNavigationHamburger__OverridesType
  dataFetches?: PlasmicNavigationHamburger__Fetches
  forNode?: string
}) {
  const { variants, args, overrides, forNode, dataFetches } = props

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <HamburgerNavigationIcon
        data-plasmic-name={"svg"}
        data-plasmic-override={overrides.svg}
        className={classNames(defaultcss.all, sty.svg)}
        role={"img"}
      />
    </div>
  ) as React.ReactElement | null
}

const PlasmicDescendants = {
  root: ["root", "svg"],
  svg: ["svg"],
} as const
type NodeNameType = keyof typeof PlasmicDescendants
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number]
type NodeDefaultElementType = {
  root: "div"
  svg: "svg"
}

type ReservedPropsType = "variants" | "args" | "overrides"
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNavigationHamburger__OverridesType,
  DescendantsType<T>
>
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNavigationHamburger__VariantsArgs
    args?: PlasmicNavigationHamburger__ArgsType
    overrides?: NodeOverridesType<T>
    dataFetches?: PlasmicNavigationHamburger__Fetches
  } & Omit<PlasmicNavigationHamburger__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicNavigationHamburger__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key }
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicNavigationHamburger__ArgProps,
      internalVariantPropNames: PlasmicNavigationHamburger__VariantProps,
    })

    const { dataFetches } = props

    return PlasmicNavigationHamburger__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicNavigationHamburger"
  } else {
    func.displayName = `PlasmicNavigationHamburger.${nodeName}`
  }
  return func
}

export const PlasmicNavigationHamburger = Object.assign(
  // Top-level PlasmicNavigationHamburger renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicNavigationHamburger
    internalVariantProps: PlasmicNavigationHamburger__VariantProps,
    internalArgProps: PlasmicNavigationHamburger__ArgProps,
  }
)

export default PlasmicNavigationHamburger
/* prettier-ignore-end */
