// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: azVx9DM13tZbR2SGxpPJBW
// Component: WLo4_NhyOe
import * as React from "react"

import { Link, GatsbyLinkProps as LinkProps } from "gatsby"

import * as p from "@plasmicapp/react-web"

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web"

import "@plasmicapp/react-web/lib/plasmic.css"
import * as defaultcss from "../plasmic__default_style.module.css" // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_underhand.module.css" // plasmic-import: azVx9DM13tZbR2SGxpPJBW/projectcss
import * as sty from "./PlasmicMainNavigation.module.css" // plasmic-import: WLo4_NhyOe/css

export type PlasmicMainNavigation__VariantMembers = {}

export type PlasmicMainNavigation__VariantsArgs = {}
type VariantPropType = keyof PlasmicMainNavigation__VariantsArgs
export const PlasmicMainNavigation__VariantProps = new Array<VariantPropType>()

export type PlasmicMainNavigation__ArgsType = {}
type ArgPropType = keyof PlasmicMainNavigation__ArgsType
export const PlasmicMainNavigation__ArgProps = new Array<ArgPropType>()

export type PlasmicMainNavigation__OverridesType = {
  root?: p.Flex<"div">
}

export interface DefaultMainNavigationProps {
  className?: string
}

function PlasmicMainNavigation__RenderFunc(props: {
  variants: PlasmicMainNavigation__VariantsArgs
  args: PlasmicMainNavigation__ArgsType
  overrides: PlasmicMainNavigation__OverridesType
  dataFetches?: PlasmicMainNavigation__Fetches
  forNode?: string
}) {
  const { variants, args, overrides, forNode, dataFetches } = props

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    />
  ) as React.ReactElement | null
}

const PlasmicDescendants = {
  root: ["root"],
} as const
type NodeNameType = keyof typeof PlasmicDescendants
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number]
type NodeDefaultElementType = {
  root: "div"
}

type ReservedPropsType = "variants" | "args" | "overrides"
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMainNavigation__OverridesType,
  DescendantsType<T>
>
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMainNavigation__VariantsArgs
    args?: PlasmicMainNavigation__ArgsType
    overrides?: NodeOverridesType<T>
    dataFetches?: PlasmicMainNavigation__Fetches
  } & Omit<PlasmicMainNavigation__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicMainNavigation__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key }
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicMainNavigation__ArgProps,
      internalVariantPropNames: PlasmicMainNavigation__VariantProps,
    })

    const { dataFetches } = props

    return PlasmicMainNavigation__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicMainNavigation"
  } else {
    func.displayName = `PlasmicMainNavigation.${nodeName}`
  }
  return func
}

export const PlasmicMainNavigation = Object.assign(
  // Top-level PlasmicMainNavigation renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicMainNavigation
    internalVariantProps: PlasmicMainNavigation__VariantProps,
    internalArgProps: PlasmicMainNavigation__ArgProps,
  }
)

export default PlasmicMainNavigation
/* prettier-ignore-end */
